package oprag.project.gestionControleDAcces.exception;

public enum ErrorCodes {

    UTILISATEUR_NOT_FOUND(1000),
    UTILISATEUR_NOT_VALID(1001),
    UTILISATEUR_EN_COURS_D_UTILSATION(1002),
    INSPECTION_EXIST(2000),
    INSPECTION_NOT_VALID(2001),
    INSPECTION_NOT_FOUND(2002),
    INSPECTION_EN_COURS_D_EXECUTION(2003),
    CERTFICAT_NOT_VALID(3000),
    CERTIFICAT_NOT_FOUND(3001),
    BADGE_NOT_FOUND(4000),
    CHAUFFEUR_ALREADY_EXIST(5000),
    CHAUFFEUR_NOT_VALID(5001),
    CHAUFFEUR_NOT_FOUND(5002),
    CHAUFFEUR_EN_COURS_D_EXECUTION(5003),
    VEHICULE_ALREADY_EXIST(6000),
    VEHICULE_NOT_VALID(6001),
    VEHICULE_NOT_FOUND(6002),
    BADGE_ALREADY_EXIST(7000),
    BADGE_NOT_VALID(7001),;

    ErrorCodes(int code){
        this.errorCode=code;
    }
    private int errorCode;

    public int getErrorCode(){
        return this.errorCode;
    }
}
