package oprag.project.gestionControleDAcces.models;

public enum EssaiFonctionnement {
    Marche_AV_AR,
    Pictogrammes_securite,
    Vibration,
    Gyrophare,
    Clignotants_AV,
    Clignotants_AR,
    Changement_de_direction,
    Trou_d_homme,
    Freinage,
    Arret_d_urgence,
    Etancheite_cuve,
    SYSTEME_DE_FREINAGE,
    SYSTEME_HYDRAULIQUE,
    CARTE_GRISE,
    ASSURANCE,
    VISITE_TECHNIQUE,
    EXTINCTEUR,
    TROUSSE_A_PHARMACIE,
    BOMBONNE_D_AIR,
    TUYAUTERIE_DU_SYSTEME_DES_REMORQUES,
    SANGLE,
    ELINGUES,
    MANILLES,
    MANOMETRE_DE_PRESSION,
    TOLERANCE_USURE_DES_PNEUS,
    INDICE_DE_VITESSE_ET_DATE_PEREMPTION,
    PERMIS_DE_CONDUIRE
}
